---
version: '3'

tasks:

  generate_presets:
    desc: Generate the first boot presets file
    cmds:
      - envsubst < {{.PRESETS_TEMPLATE}} > {{.PRESETS_OUTPUT}}
    vars:
      PRESETS_TEMPLATE: "{{.ROOT_DIR}}/presets.template"
      PRESETS_OUTPUT: "{{.ROOT_DIR}}/userpatches/overlay/root/.not_logged_in_yet"
    env:
      ROOT_PASSWORD:
        sh: security find-generic-password -s rk1-armbian-k3s -a root -w
      USER_PASSWORD:
        sh: security find-generic-password -s rk1-armbian-k3s -a user -w
